spring.application.name=aula

spring.web.resources.add-mappings=false

# ConfiguraÃ§Ãµes do datasource
spring.datasource.url=${JDBC_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ConfiguraÃ§Ãµes do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

